### ISSUE TITLE
Output `bcInfo` in `.csv`

### ISSUE THREAD

**Issue by khdusenbury** [jbloomlab/dms_tools2#41]
It would make downstream analyses more flexible if the final output containing the barcode info from `dms2_bcsubamp` was in `.csv` format.

https://github.com/jbloomlab/dms_tools2/blob/d658fed9ef7410f1cfda7b31c8cdc38b3e29cf87/scripts/dms2_bcsubamp#L40-L48

**Comment by jbloom** [comment]
I'm fine with adding this change, although note that it's not exactly clear how the currently returned data is converted to CSV since some things (like R1 reads) are lists.

But if you want to make a change like this, I would suggest adding an additonal option like `--bcinfo-csv` to the program and making it return the file in the format you want?

**Comment by khdusenbury** [comment]
Sounds good. I agree with making it an option. I'll think on it a bit, but it seems most people just use the consensus for downstream analyses. I think my plan would be to just include the number of R1 and R2 reads, rather than the lists of those reads, that go into making the consensus

**Comment by khdusenbury** [comment]
I made a local branch of `dms_tools2` and added a `bcinfo_csv` option, but I'm not sure how developing `dms_tools2` is supposed to work, so am not sure how to proceed. 

I also ran into issues with already having `dms_tools2` installed locally, and the tests always using that instead of my edited version, so I wasn't able to fully test, but I did a couple small tests that seemed to work. Perhaps we can discuss when we meet next week.

**Comment by jbloom** [comment]
If you think your version is ready, just do the same thing we did for `alignparse`. Push your changes to a branch and then initiate a pull request. Make sure you have some sort of small test for what you added.

If you have local installs, you should be able to remove them all with `~/.local` and then do `python setup.py develop --user` to install the development version in `~/.local`.

Note that if you are running command-line programs rather than python imports, you also need this line at the end of your `~/.bashrc`:
```
PATH="$HOME/.local/bin:$PATH"
```

See the [Developing Python software locally instructions](https://github.com/jbloomlab/software/blob/master/README.md) for the BloomLab conda environment.

**Comment by jbloom** [comment]
Addressed by pull request #42
